# look at /usr/include/linux/input-event-codes.h to find keycodes for ydotool
# ctrl = 29, shift = 42, alt = 56, super = 125, escape = 1
swipe:
    3:
        left:
          # begin: 
          #   command: 'ydotool key --key-delay 1 56:1'
          # update:
          #   command: 'xdotool key Tab'
          update:
            #sendkey: "LEFTCTRL+NEXT"
            # command: xte 'keydown Control_L' 'key Next' 'keyup Control_L'
            command: |-
                window=$(xdotool getactivewindow)
                case $(xprop -id $window WM_CLASS | cut -d \" -f 4) in
                    Spotify)
                        xte 'key XF86AudioNext'
                        ;;
                    *)
                        ydotool key --key-delay 0 29:1 109:1 109:0 29:0
                        ;;
                esac
            threshold: 1.1
            interval: 1.6
        right:
          update:
            #sendkey: "LEFTCTRL+PREVIOUS"
            # command: xte 'keydown Control_L' 'key Prior' 'keyup Control_L'
            command:  |-
                window=$(xdotool getactivewindow)
                case $(xprop -id $window WM_CLASS | cut -d \" -f 4) in
                    Spotify)
                        xte 'key XF86AudioPrev'
                        ;;
                    *)
                        ydotool key --key-delay 0 29:1 104:1 104:0 29:0
                        ;;
                esac
            threshold: 1.1
            interval: 1.6
        up:
          #update:
            #command: xte 'keydown Control_L' 'key F4' 'keyup Control_L'
            # command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix) xte 'keydown Control_L' 'keydown Shift_L' 'key W' 'keyup Shift_L' 'keyup Control_L';; kitty|Firefox|"Firefox Developer Edition"|"Tor Browser") xte 'keydown Control_L' 'key F4' 'keyup Control_L';; *) xte 'keydown Control_L' 'key W' 'keyup Control_L';; esac
            command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix) ydotool key --key-delay 0 29:1 42:1 17:1 17:0 42:0 29:0 ;; kitty|firefox|"Firefox Developer Edition"|"Tor Browser") ydotool key --key-delay 0 29:1 62:1 62:0 29:0 ;; *) ydotool key --key-delay 0 29:1 17:1 17:0 29:0 ;; esac
            threshold: 0.9
            # interval: 2.0
        down:
          #update:
            #command: xte 'keydown Control_L' 'keydown Shift_L' 'key T' 'keyup Shift_L' 'keyup Control_L'
            # command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix|kitty) xte 'keydown Control_L' 'keydown Shift_L' 'key T' 'keyup Shift_L' 'keyup Control_L';; TeXstudio) xte 'keydown Control_L' 'key N' 'keyup Control_L';; "") xte 'keydown Control_L' 'keydown Alt_L' 'key T' 'keyup Alt_L' 'keyup Control_L';; *) xte 'keydown Control_L' 'key T' 'keyup Control_L';; esac
            command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix|kitty) ydotool key --key-delay 0 29:1 42:1 20:1 20:0 42:0 29:0 ;; TeXstudio) ydotool key --key-delay 0 29:1 49:1 49:0 29:0 ;; "") ydotool key --key-delay 0 29:1 56:1 20:1 20:0 56:0 29:0 ;; *) ydotool key --key-delay 0 29:1 20:1 20:0 29:0 ;; esac
            #if [[ $(xdotool getwindowfocus getwindowname) =~ ".*Firefox$" ]]; then
                #xte 'keydown Control_L' 'key T' 'keyup Control_L';
            #else
                #xte 'keydown Control_L' 'keydown Shift_L' 'key T' 'keyup Shift_L' 'keyup Control_L';
            #fi
            threshold: 0.8
            #interval: 3.1
    4:
        left:
            command: |-
                window=$(xdotool getactivewindow)
                case $(xprop -id $window WM_CLASS | cut -d '"' -f 4) in
                    Tilix|kitty)
                        if echo $(xprop -id $window WM_NAME | cut -d '"' -f 2) | grep "^nvim:"; then
                            # xte 'keydown Control_L' 'keydown Alt_L' 'key Next' 'keyup Alt_L' 'keyup Control_L' 
                            ydotool key --key-delay 0 29:1 56:1 109:1 109:0 56:0 29:0 
                        else
                            xte 'key Down'
                        fi
                        ;;
                    Rhythmbox)
                        xte 'key XF86AudioNext'
                        ;;
                    *)
                        # xte 'keydown Alt_L' 'key Right' 'keyup Alt_L'
                        ydotool key --key-delay 0 56:1 106:1 106:0 56:0
                        ;;
                esac
            threshold: 0.3
        right:
            #command: case $(xdotool getactivewindow getwindowname) in "Tilix:"*) xte 'key Up';; *) xte 'keydown Alt_L' 'key Left' 'keyup Alt_L';; esac
            #command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix|kitty"") xte 'key Up';; case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix|kitty) xte 'key Up';; Rhythmbox) xte 'key XF86AudioPrev';; *) xte 'keydown Alt_L' 'key Left' 'keyup Alt_L';; esac
            command: |-
                window=$(xdotool getactivewindow)
                case $(xprop -id $window WM_CLASS | cut -d \" -f 4) in
                    Tilix|kitty)
                        if echo $(xprop -id $window WM_NAME | cut -d '"' -f 2) | grep "^nvim:"; then
                            # xte 'keydown Control_L' 'keydown Alt_L' 'key Prior' 'keyup Alt_L' 'keyup Control_L' 
                            ydotool key --key-delay 0 29:1 56:1 104:1 104:0 56:0 29:0 
                        else
                            xte 'key Up'
                        fi
                        ;;
                    Rhythmbox)
                        xte 'key XF86AudioPrev'
                        ;;
                    *)
                        # xte 'keydown Alt_L' 'key Left' 'keyup Alt_L'
                        ydotool key --key-delay 0 56:1 105:1 105:0 56:0
                        ;;
                esac
            threshold: 0.3
        down:
            # command: xte 'keydown Super_L' 'key Prior' 'keyup Super_L'
            command: ydotool key --key-delay 0 125:1 104:1 104:0 125:0
            threshold: 0.7
        up:
            # command: xte 'keydown Super_L' 'key Next' 'keyup Super_L'
            command: ydotool key --key-delay 0 125:1 109:1 109:0 125:0
            threshold: 0.7
pinch:
    #2:
    #    in:
    #        window:
    #            maximized: add
    #            threshold: 0.05
    #    out:
    #        # window:
    #        #     maximized: remove
    #        #     threshold: 0.27
    #        #command: if [[ `xwininfo -id $(xdotool getactivewindow) | grep geometry` = `xwininfo -root | grep geometry` ]]; then wmctrl -r :ACTIVE: -b remove,fullscreen; else wmctrl -r :ACTIVE: -b remove,maximized; fi
    #        command: if [ "$(xwininfo -id $(xdotool getactivewindow) | grep geometry)" = "  -geometry 1920x1080+0+0" ]; then case $(tr "\0" " " < /proc/$(xdotool getactivewindow getwindowpid)/cmdline) in "/usr/bin/vlc "*) xte 'key F';; "xournalpp "*) xte 'key F11';; *) wmctrl -r ':ACTIVE:' -b remove,fullscreen;; esac; else wmctrl -r ':ACTIVE:' -b remove,maximized_vert,maximized_horz; fi
    #        threshold: 1.0
    3:
        in:
            # command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix) xte 'keydown Alt_L' 'key Escape' 'keyup Alt_L';; *) xte 'keydown Super_L' 'key 4' 'keyup Super_L';; esac
            command: case $(xprop -id $(xdotool getactivewindow) WM_CLASS | cut -d '"' -f 4) in Tilix) ydotool key --key-delay 0 56:1 1:1 1:0 56:0 ;; *) ydotool key --key-delay 0 125:1 5:1 5:0 125:0 ;; esac
            threshold: 0.8
        out:
            # command: xte 'keydown Super_L' 'key S' 'keyup Super_L'
            command: ydotool key --key-delay 0 125:1 125:0
            threshold: 0.7
    4:
        in:
            # command: xte 'keydown Alt_L' 'keydown Shift_L' 'key Tab' 'keyup Shift_L' 'keyup Alt_L'
            command: ydotool key --key-delay 0 56:1 42:1 15:1 15:0 42:0 56:0
            threshold: 0.75
        out:
            # command: xte 'keydown Alt_L' 'key Tab' 'keyup Alt_L'
            command: ydotool key --key-delay 0 56:1 15:1 15:0 56:0
            threshold: 0.7
